### ISSUE TITLE
Unable to start on server

### ISSUE THREAD

**Issue by wbsp9999** [NinjaPhenix/ExpandedStorage#22]
Hey I was testing your mod out and all works fine if I just use it client-side, but when trying to add to a server (even w/ no other mods, just fabric-api) I get this error:

```
        - expandedstorage@7.0.0-alpha.31
        - fabric@0.36.0+1.17
        - fabric-api-base@0.3.0+a02b44633d
....
[15:26:34] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expandedstorage'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_304
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtilsImpl.<init>(PlatformUtilsImpl.java:35) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtilsImpl.getInstance(PlatformUtilsImpl.java:40) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtils.getInstance(PlatformUtils.java:23) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.internal_api.Utils.<clinit>(Utils.java:34) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.config.ConfigV0.<init>(ConfigV0.java:14) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.ConfigWrapperImpl.getConfig(ConfigWrapperImpl.java:109) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.ConfigWrapperImpl.initialise(ConfigWrapperImpl.java:38) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.BaseCommon.initialize(BaseCommon.java:37) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.Main.onInitialize(Main.java:21) ~[expanded-storage.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtilsImpl.<init>(PlatformUtilsImpl.java:35) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtilsImpl.getInstance(PlatformUtilsImpl.java:40) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.PlatformUtils.getInstance(PlatformUtils.java:23) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.internal_api.Utils.<clinit>(Utils.java:34) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.config.ConfigV0.<init>(ConfigV0.java:14) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.ConfigWrapperImpl.getConfig(ConfigWrapperImpl.java:109) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.wrappers.ConfigWrapperImpl.initialise(ConfigWrapperImpl.java:38) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.BaseCommon.initialize(BaseCommon.java:37) ~[expanded-storage.jar:?]
        at ninjaphenix.expandedstorage.base.Main.onInitialize(Main.java:21) ~[expanded-storage.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
```

Any help would be appreciated!

**Comment by NinjaPhenix** [comment]
Been made aware earlier in day, fixing it right now just going to fix another issue first before releasing.

**Comment by NinjaPhenix** [comment]
Fixed in release 32, thanks for reporting.
